IP="192.168.0.150"

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  # ELASTIC NODE
  config.vm.define "elastic" do |elastic|
    elastic.vm.hostname = "elastic"

    elastic.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 1
    end
    elastic.vm.network "public_network", ip: IP, bridge: "enp5s0"

    elastic.vm.provision "shell", path: "scripts/common.sh"
    elastic.vm.provision "file", source: "./config/", destination: "~/elastic/config"
    elastic.vm.provision "file", source: "./docker-compose.yml", destination: "~/elastic/docker-compose.yml"
  end

end