IP_PUB_NW="192.168.10."
IP_NW="10.0.0."

IP_START_MASTERS=10
NUM_MASTERS_NODES=2

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false

  # MASTER NODE
  config.vm.define "master-01" do |master|
    master.vm.hostname = "master-01"
    master.vm.network "private_network", ip: IP_NW + "#{IP_START_MASTERS+1}"
    master.vm.network "public_network", ip: IP_PUB_NW + "#{IP_START_MASTERS+1}", bridge: "enp5s0"

    master.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
    end

    master.vm.provision "shell", path: "scripts/common.sh"
    master.vm.provision "shell", path: "scripts/master.sh"
    master.vm.provision "shell", path: "scripts/elastic-agent.sh"
    master.vm.provision "shell", path: "scripts/fleet-server.sh"
    master.vm.provision "shell", inline: "sudo docker network create -d overlay application"
    master.vm.provision "file", source: "./nginx/", destination: "~/nginx"
  end

  # MORE MASTER NODES
  (1..NUM_MASTERS_NODES).each do |i|
    config.vm.define "master-0#{i+1}" do |master|
      master.vm.hostname = "master-0#{i+1}"
      master.vm.network "private_network", ip: IP_NW + "#{IP_START_MASTERS+i+1}"
      master.vm.network "public_network", ip: IP_PUB_NW + "#{IP_START_MASTERS+i+1}", bridge: "enp5s0"
      
      master.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
      master.vm.provision "shell", path: "scripts/common.sh"
      master.vm.provision "shell", path: "scripts/join-master.sh"
      master.vm.provision "shell", path: "scripts/elastic-agent.sh"
      master.vm.provision "shell", path: "scripts/fleet-server.sh"
    end
  end

  # HAPROXY NODE
  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.hostname = "haproxy"

    haproxy.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    haproxy.vm.network "public_network", ip: IP_PUB_NW + "200", bridge: "enp5s0"
    haproxy.vm.provision "shell", path: "scripts/haproxy.sh"
    haproxy.vm.provision "shell", path: "scripts/elastic-agent.sh"
    haproxy.vm.provision "shell", path: "scripts/fleet-server.sh"
  end

end