version: '3.9'

networks:
  application:
    driver: overlay
    attachable: true

services:
  node-api:
    container_name: node-api
    image: gabrielroque/api-node-example:v3
    command: sh -c "npm start"
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - application
    ports:
      - 8080:8080
  nginx:
    container_name: nginx
    image: gabrielroque/nginx-cluster:v1
    restart: always
    networks:
      - application
    depends_on:
      - node-api
    ports:
      - 80:80
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
